# -*- coding: utf-8 -*-
"""urban_institute_api_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDhRpkCvEcaSWEMGY-XtbOONPN_DIy2b

# Education Data API Exploration

## Objective
Demonstrate ability to:
- Make REST API calls
- Apply filters
- Parse JSON responses
- Convert data to structured format
- Prepare data for reporting

## Endpoints Used
- CCD Directory 2013
- CCD Enrollment Grade 3 (Charter, DC filter)
"""

import requests
import json

url="https://educationdata.urban.org/api/v1/schools/ccd/directory/2013/"

response = requests.get(url)

print("Status Code", response.status_code)

data = response.json()

print(json.dumps(data, indent=2)[:2000])


#Hits a REST API endpoint, validates the status code, parses the JSON

url = "https://educationdata.urban.org/api/v1/schools/ccd/enrollment/2015/grade-3/?charter=1&fips=11"

response = requests.get(url)
data = response.json()

print("Number of Records:", len(data["results"]))
print(json.dumps(data["results"][:5], indent=2))

#Uses endpoint modifiers, adds query parameters, handles structured responses

import pandas as pd
df = pd.DataFrame(data["results"])
df.head()

#Pulls API data, converts JSON into dataframe, makes it analysis-ready